### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ctrlcctrlv** [den32ds/Teleindicadores1#1]
It is not enough to say, as you have, &laquo;this font is in the public domain.&raquo;

That has a different meaning in different countries; in many countries it has no legal meaning at all in regards to copyright.

If you would like to release the font into the public domain, please add license e.g. CC0 license.

Most open source fonts are under SIL OFL. I recommend that instead. Always good to see new fonts being released, especially ones made in FontForge, which I am a maintainer of.

Thank you for the cool font, a big thank you for *using Unicode*, ☺, ▓, etc. Yo no s&eacute; nada de Espa&ntilde;a, s&oacute;lo M&eacute;xico; pero en mi opinión, esta fuente es aplicable en todo el mundo, no solo España.

![ty](https://user-images.githubusercontent.com/838783/61298576-0f881e00-a811-11e9-938c-ae283c9b2dc6.png)

**Comment by rellikmil** [comment]
@ctrlcctrlv Thanks for you issue. Original creator published this font under public domain without license, so you can do everything. But if you want, I will add WTFPL license because she`s simple than CC0. And this font is not new, I just improved Cyrillic.
P.S. Please improve Cyrillic in your font "LCD"
![thanks](https://user-images.githubusercontent.com/24569064/62364981-8de00200-b52b-11e9-9971-641bc5b72477.png)

**Comment by rellikmil** [comment]
Ok, I added Unlicense

**Comment by ctrlcctrlv** [comment]
Thanks

Regarding my LCD font, I will remake it some day, I'm not sure when though. Good to see someone likes it, that's not one of my more popular ones. :-)

**Comment by rellikmil** [comment]
@ctrlcctrlv Do you know where to find information about OpenType features, how to prescribe them etc. (preferably in Russian), i didn`t find

**Comment by ctrlcctrlv** [comment]
I don't know where to find any information in Russian as I don't speak the language. I hear Yandex is good, I learned that from some podcast, good for them for taking power away from Google, even if only in Russia.

**Comment by rellikmil** [comment]
@ctrlcctrlv I mean books, articles how make OpenType features. And I said "preferably", so English primarily.

**Comment by rellikmil** [comment]
Podcast? Hmmm, with my knowledge of English it will be difficult
